-- Migration 004: Artifacts table
-- Stores charts, tables, images, and files generated by DAWN

CREATE TABLE IF NOT EXISTS artifacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('chart', 'table', 'image', 'file')),
    title TEXT NOT NULL,
    description TEXT,
    spec JSONB,          -- Vega-Lite spec for charts
    url TEXT,            -- URL for images/files
    data_summary TEXT,   -- Text summary of what this artifact shows
    tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for listing artifacts by session
CREATE INDEX IF NOT EXISTS idx_artifacts_session_id ON artifacts(session_id);

-- Index for filtering by type
CREATE INDEX IF NOT EXISTS idx_artifacts_type ON artifacts(type);

-- Index for ordering by creation time
CREATE INDEX IF NOT EXISTS idx_artifacts_created_at ON artifacts(created_at DESC);

-- Enable RLS
ALTER TABLE artifacts ENABLE ROW LEVEL SECURITY;

-- Allow all operations for authenticated users
CREATE POLICY "Allow all for authenticated users" ON artifacts
    FOR ALL
    USING (true)
    WITH CHECK (true);
