"use client";

import { useState, useEffect, useCallback } from "react";
import AppShell from "@/components/layout/AppShell";
import ChartRenderer from "@/components/visualize/ChartRenderer";
import { listArtifacts, deleteArtifact } from "@/lib/api";
import type { Artifact } from "@/lib/types";
import {
  BarChart3,
  Table2,
  Image,
  FileText,
  Trash2,
  Search,
  Filter,
  Loader2,
  AlertCircle,
  ExternalLink,
  Clock,
  Tag,
} from "lucide-react";
import clsx from "clsx";

const TYPE_ICONS: Record<string, React.ElementType> = {
  chart: BarChart3,
  table: Table2,
  image: Image,
  file: FileText,
};

const TYPE_COLORS: Record<string, string> = {
  chart: "text-dawn bg-dawn/10 border-dawn/20",
  table: "text-blue-400 bg-blue-400/10 border-blue-400/20",
  image: "text-emerald-400 bg-emerald-400/10 border-emerald-400/20",
  file: "text-amber-400 bg-amber-400/10 border-amber-400/20",
};

function ArtifactsContent() {
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState<string>("all");
  const [selectedArtifact, setSelectedArtifact] = useState<Artifact | null>(null);

  const fetchArtifacts = useCallback(async () => {
    try {
      setLoading(true);
      const data = await listArtifacts();
      setArtifacts(data);
      setError(null);
    } catch (err) {
      console.error("[Artifacts] Failed to load:", err);
      setError("Failed to load artifacts");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchArtifacts();
  }, [fetchArtifacts]);

  const handleDelete = async (id: string) => {
    try {
      await deleteArtifact(id);
      setArtifacts((prev) => prev.filter((a) => a.id !== id));
      if (selectedArtifact?.id === id) setSelectedArtifact(null);
    } catch (err) {
      console.error("[Artifacts] Failed to delete:", err);
    }
  };

  const filtered = artifacts.filter((a) => {
    if (typeFilter !== "all" && a.type !== typeFilter) return false;
    if (search) {
      const q = search.toLowerCase();
      return (
        a.title.toLowerCase().includes(q) ||
        (a.description || "").toLowerCase().includes(q) ||
        (a.data_summary || "").toLowerCase().includes(q)
      );
    }
    return true;
  });

  const timeAgo = (dateStr: string) => {
    const date = new Date(dateStr);
    const mins = Math.floor((Date.now() - date.getTime()) / 1000 / 60);
    if (mins < 1) return "just now";
    if (mins < 60) return `${mins}m ago`;
    const hours = Math.floor(mins / 60);
    if (hours < 24) return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    if (days < 30) return `${days}d ago`;
    return `${Math.floor(days / 30)}mo ago`;
  };

  return (
    <div className="flex h-full">
      {/* Main list */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Header */}
        <div className="flex-shrink-0 border-b border-rim px-4 sm:px-6 py-3">
          <div className="flex items-center justify-between mb-3">
            <div>
              <h1 className="text-text-primary text-sm font-semibold">Artifacts</h1>
              <p className="text-text-muted text-2xs mt-0.5">
                Charts, tables, and files generated by DAWN
              </p>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-text-muted text-2xs font-mono">
                {filtered.length} / {artifacts.length}
              </span>
            </div>
          </div>

          {/* Search + filter */}
          <div className="flex items-center gap-2">
            <div className="flex-1 relative">
              <Search size={12} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-text-muted" />
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search artifacts..."
                className="w-full bg-elevated/60 border border-rim rounded-lg pl-7 pr-3 py-1.5 text-xs text-text-primary placeholder:text-text-muted outline-none focus:border-dawn/40 transition-all"
              />
            </div>
            <div className="flex items-center gap-1">
              {["all", "chart", "table", "image", "file"].map((t) => (
                <button
                  key={t}
                  onClick={() => setTypeFilter(t)}
                  className={clsx(
                    "px-2 py-1 rounded-md text-2xs font-medium capitalize transition-all",
                    typeFilter === t
                      ? "bg-dawn/15 text-dawn border border-dawn/30"
                      : "text-text-muted hover:text-text-secondary border border-transparent"
                  )}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Grid */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6">
          {loading ? (
            <div className="flex items-center justify-center h-full">
              <Loader2 size={20} className="text-dawn animate-spin" />
            </div>
          ) : error ? (
            <div className="flex flex-col items-center justify-center h-full gap-2">
              <AlertCircle size={18} className="text-ember" />
              <p className="text-text-muted text-sm">{error}</p>
              <button
                onClick={fetchArtifacts}
                className="px-3 py-1.5 rounded-lg bg-dawn/10 text-dawn text-xs hover:bg-dawn/20 transition-all"
              >
                Retry
              </button>
            </div>
          ) : filtered.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full gap-2">
              <BarChart3 size={24} className="text-text-muted/50" />
              <p className="text-text-muted text-sm">
                {artifacts.length === 0
                  ? "No artifacts yet. Ask DAWN to visualize something!"
                  : "No artifacts match your filter"}
              </p>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {filtered.map((artifact) => {
                const Icon = TYPE_ICONS[artifact.type] || FileText;
                const colorClass = TYPE_COLORS[artifact.type] || "text-text-muted bg-elevated/60 border-rim";
                return (
                  <button
                    key={artifact.id}
                    onClick={() => setSelectedArtifact(artifact)}
                    className="text-left p-3 rounded-xl bg-surface border border-rim hover:border-dawn/30 transition-all group"
                  >
                    <div className="flex items-start justify-between mb-2">
                      <div className={clsx("w-8 h-8 rounded-lg flex items-center justify-center border", colorClass)}>
                        <Icon size={14} />
                      </div>
                      <button
                        onClick={(e) => { e.stopPropagation(); handleDelete(artifact.id); }}
                        className="w-6 h-6 flex items-center justify-center rounded text-text-muted opacity-0 group-hover:opacity-100 hover:text-ember transition-all"
                        title="Delete"
                      >
                        <Trash2 size={10} />
                      </button>
                    </div>
                    <h3 className="text-text-primary text-xs font-medium truncate">{artifact.title}</h3>
                    {artifact.description && (
                      <p className="text-text-muted text-2xs mt-0.5 line-clamp-2">{artifact.description}</p>
                    )}
                    <div className="flex items-center gap-2 mt-2">
                      <span className="flex items-center gap-1 text-text-muted text-2xs">
                        <Clock size={9} />
                        {timeAgo(artifact.created_at)}
                      </span>
                      {artifact.tags && artifact.tags.length > 0 && (
                        <span className="flex items-center gap-1 text-text-muted text-2xs">
                          <Tag size={9} />
                          {artifact.tags.length}
                        </span>
                      )}
                    </div>
                  </button>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Detail panel */}
      {selectedArtifact && (
        <div className="w-96 border-l border-rim bg-surface/80 backdrop-blur-sm overflow-y-auto flex-shrink-0 hidden lg:block">
          <div className="p-4">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                {(() => {
                  const Icon = TYPE_ICONS[selectedArtifact.type] || FileText;
                  const colorClass = TYPE_COLORS[selectedArtifact.type] || "text-text-muted bg-elevated/60 border-rim";
                  return (
                    <div className={clsx("w-8 h-8 rounded-lg flex items-center justify-center border", colorClass)}>
                      <Icon size={14} />
                    </div>
                  );
                })()}
                <div>
                  <h3 className="text-text-primary text-sm font-medium">{selectedArtifact.title}</h3>
                  <span className="text-text-muted text-2xs capitalize">{selectedArtifact.type}</span>
                </div>
              </div>
              <button
                onClick={() => setSelectedArtifact(null)}
                className="w-6 h-6 flex items-center justify-center rounded text-text-muted hover:text-text-secondary"
              >
                <span className="text-xs">✕</span>
              </button>
            </div>

            {/* Render chart if it has a spec */}
            {selectedArtifact.type === "chart" && selectedArtifact.spec && (
              <div className="mb-4">
                <ChartRenderer spec={selectedArtifact.spec} title={selectedArtifact.title} />
              </div>
            )}

            {/* Image */}
            {selectedArtifact.type === "image" && selectedArtifact.url && (
              <div className="mb-4 rounded-xl overflow-hidden border border-rim">
                <img
                  src={selectedArtifact.url}
                  alt={selectedArtifact.title}
                  className="w-full h-auto"
                />
              </div>
            )}

            {/* Description */}
            {selectedArtifact.description && (
              <div className="mb-3">
                <h4 className="text-text-muted text-2xs font-medium uppercase tracking-wider mb-1">Description</h4>
                <p className="text-text-primary text-xs">{selectedArtifact.description}</p>
              </div>
            )}

            {/* Data summary */}
            {selectedArtifact.data_summary && (
              <div className="mb-3">
                <h4 className="text-text-muted text-2xs font-medium uppercase tracking-wider mb-1">Summary</h4>
                <p className="text-text-primary text-xs">{selectedArtifact.data_summary}</p>
              </div>
            )}

            {/* Tags */}
            {selectedArtifact.tags && selectedArtifact.tags.length > 0 && (
              <div className="mb-3">
                <h4 className="text-text-muted text-2xs font-medium uppercase tracking-wider mb-1">Tags</h4>
                <div className="flex flex-wrap gap-1">
                  {selectedArtifact.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-1.5 py-0.5 rounded bg-elevated/60 border border-rim text-text-muted text-2xs"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Metadata */}
            <div className="text-text-muted text-2xs space-y-1">
              <p>Created: {new Date(selectedArtifact.created_at).toLocaleString()}</p>
              <p>ID: <span className="font-mono">{selectedArtifact.id.slice(0, 12)}...</span></p>
            </div>

            {/* Actions */}
            <div className="mt-4 flex gap-2">
              <button
                onClick={() => handleDelete(selectedArtifact.id)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-rim text-text-muted hover:text-ember hover:border-ember/30 transition-all text-xs"
              >
                <Trash2 size={11} />
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default function ArtifactsPage() {
  return (
    <AppShell>
      <ArtifactsContent />
    </AppShell>
  );
}
