"""
Artifacts router — CRUD for charts, tables, images, and files generated by DAWN.
Stored in the `artifacts` table in Supabase.
"""
import logging
from fastapi import APIRouter, Depends, HTTPException, Header
from typing import Optional
from pydantic import BaseModel
import db.client as db
from config import settings

logger = logging.getLogger(__name__)

router = APIRouter()


# ── Auth ──────────────────────────────────────────────────────────────────────

def verify_key(x_api_key: Optional[str] = Header(None)):
    if x_api_key != settings.dawn_api_key:
        raise HTTPException(status_code=401, detail="Invalid API key")


# ── Schema ─────────────────────────────────────────────────────────────────────

class ArtifactCreate(BaseModel):
    session_id: str
    type: str  # "chart" | "table" | "image" | "file"
    title: str
    description: Optional[str] = None
    spec: Optional[dict] = None  # Vega-Lite spec for charts
    url: Optional[str] = None
    data_summary: Optional[str] = None
    tags: list[str] = []


class ArtifactUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    tags: Optional[list[str]] = None


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/")
async def list_artifacts(
    type: Optional[str] = None,
    session_id: Optional[str] = None,
    limit: int = 50,
    offset: int = 0,
    _: None = Depends(verify_key),
):
    """List artifacts with optional type and session_id filters."""
    try:
        supabase = db.get_db()
        query = supabase.table("artifacts").select("*", count="exact")

        if type:
            query = query.eq("type", type)
        if session_id:
            query = query.eq("session_id", session_id)

        query = query.order("created_at", desc=True).range(offset, offset + limit - 1)
        res = query.execute()

        return res.data or []
    except Exception as e:
        logger.error(f"[artifacts] Failed to list: {e}")
        raise HTTPException(status_code=500, detail="Failed to list artifacts")


@router.get("/count")
async def count_artifacts(
    type: Optional[str] = None,
    _: None = Depends(verify_key),
):
    """Count artifacts, optionally filtered by type."""
    try:
        supabase = db.get_db()
        query = supabase.table("artifacts").select("*", count="exact", head=True)

        if type:
            query = query.eq("type", type)

        res = query.execute()
        return {"total": res.count or 0}
    except Exception as e:
        logger.error(f"[artifacts] Failed to count: {e}")
        raise HTTPException(status_code=500, detail="Failed to count artifacts")


@router.get("/{artifact_id}")
async def get_artifact(
    artifact_id: str,
    _: None = Depends(verify_key),
):
    """Get a single artifact by ID."""
    try:
        supabase = db.get_db()
        res = supabase.table("artifacts").select("*").eq("id", artifact_id).execute()
        if not res.data:
            raise HTTPException(status_code=404, detail="Artifact not found")
        return res.data[0]
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[artifacts] Failed to get {artifact_id}: {e}")
        raise HTTPException(status_code=500, detail="Failed to get artifact")


@router.post("/")
async def create_artifact(
    req: ArtifactCreate,
    _: None = Depends(verify_key),
):
    """Create a new artifact."""
    try:
        supabase = db.get_db()
        data = {
            "session_id": req.session_id,
            "type": req.type,
            "title": req.title,
        }
        if req.description:
            data["description"] = req.description
        if req.spec:
            data["spec"] = req.spec
        if req.url:
            data["url"] = req.url
        if req.data_summary:
            data["data_summary"] = req.data_summary
        if req.tags:
            data["tags"] = req.tags

        res = supabase.table("artifacts").insert(data).execute()
        if not res.data:
            raise HTTPException(status_code=500, detail="Failed to create artifact")
        return res.data[0]
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[artifacts] Failed to create: {e}")
        raise HTTPException(status_code=500, detail="Failed to create artifact")


@router.put("/{artifact_id}")
async def update_artifact(
    artifact_id: str,
    req: ArtifactUpdate,
    _: None = Depends(verify_key),
):
    """Update an artifact's metadata."""
    try:
        supabase = db.get_db()
        data = {}
        if req.title is not None:
            data["title"] = req.title
        if req.description is not None:
            data["description"] = req.description
        if req.tags is not None:
            data["tags"] = req.tags

        if not data:
            raise HTTPException(status_code=400, detail="No fields to update")

        res = supabase.table("artifacts").update(data).eq("id", artifact_id).execute()
        if not res.data:
            raise HTTPException(status_code=404, detail="Artifact not found")
        return res.data[0]
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[artifacts] Failed to update {artifact_id}: {e}")
        raise HTTPException(status_code=500, detail="Failed to update artifact")


@router.delete("/{artifact_id}")
async def delete_artifact(
    artifact_id: str,
    _: None = Depends(verify_key),
):
    """Delete an artifact."""
    try:
        supabase = db.get_db()
        res = supabase.table("artifacts").delete().eq("id", artifact_id).execute()
        if not res.data:
            raise HTTPException(status_code=404, detail="Artifact not found")
        return {"status": "deleted", "id": artifact_id}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[artifacts] Failed to delete {artifact_id}: {e}")
        raise HTTPException(status_code=500, detail="Failed to delete artifact")
